apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: lets-chat
    tier: backend
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: lets-chat-mongo-port